# Generated by Django 5.2.4 on 2025-08-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField()),
                ('major', models.CharField()),
                ('location', models.CharField()),
                ('start_date', models.CharField(null=True)),
                ('end_date', models.CharField(null=True)),
                ('gpa', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages_list', models.CharField()),
                ('frameworks_list', models.CharField()),
                ('tools_list', models.CharField()),
                ('technologies_list', models.CharField()),
                ('databases_list', models.CharField()),
                ('certificates_list', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('organisation', models.CharField()),
                ('location', models.CharField()),
                ('start_date', models.CharField()),
                ('end_date', models.CharField()),
                ('included', models.BooleanField(default=False)),
                ('descriptions', models.ManyToManyField(to='resume.description')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('tools', models.CharField()),
                ('source_code', models.CharField()),
                ('descriptions', models.ManyToManyField(to='resume.description')),
            ],
        ),
    ]
