# Generated by Django 5.2.5 on 2025-08-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_rename_technicalskills_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='descriptions',
            field=models.ManyToManyField(null=True, to='resume.description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(null=True),
        ),
    ]
