# Generated by Django 5.2.5 on 2025-08-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_experience_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='descriptions',
            field=models.ManyToManyField(blank=True, null=True, to='resume.description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='included',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='descriptions',
            field=models.ManyToManyField(blank=True, null=True, to='resume.description'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='certificates_list',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='databases_list',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='frameworks_list',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='languages_list',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='technologies_list',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='tools_list',
            field=models.CharField(blank=True, null=True),
        ),
    ]
