# Generated by Django 5.2.5 on 2025-08-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_rename_title_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='source_code',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.CharField(blank=True, null=True),
        ),
    ]
