# Generated by Django 5.2.5 on 2025-08-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_project_source_code_alter_project_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='content',
            field=models.CharField(),
        ),
    ]
