# Generated by Django 5.2.5 on 2025-09-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_description_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
