# Generated by Django 5.2.5 on 2025-09-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_skill_delete_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='included',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
